### ISSUE TITLE
Time Inconsistency

### ISSUE THREAD

**Issue by EMREOYUN** [GNimrodG/simrail-map-optimized#19]
While on the map, the time is shown incorrectly(UTC +1 is 9:17 PM instead of 10:17 PM). For that reason, timetable arrivals are displayed incorrectly. The screenshotted computer is in UTC +3 without daylight saving.
![image](https://github.com/GNimrodG/simrail-map-optimized/assets/35144629/acfa963f-2689-40aa-8f3d-99fa0ea5f811)

**Comment by GNimrodG** [comment]
Thank you for reporting this issue. I have published a fixed version. If you continue to experience any problems, please let me know by reporting it here.
